# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      #- image: circleci/python:3.6.1
      - image: dragas/nikola:alpine
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
Vs
      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: create build
          command: |
            #. venv/bin/activate
            nikola build
            git clone https://github.com/vikasontech/web.git
            git config --global user.email "vikas.on@gmail.com"
            git config --global user.name "vikas cicd"
            cd web
            git checkout -b cicd
            cp -rf ../output/ ./
            git add *
            git commit -am  "deployied by cicd"
            git push --set-upstream origin cicd
            echo "success"

